name = "pkmn-team"
type = "javascript"
compatibility_date = "2022-02-05"

route = "pkmn-team.bekapod.codes/*"
zone_id = ""

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = "true"

[build.upload]
format = "service-worker"

[vars]
SENTRY_ENABLE_DEBUG = "false"
SENTRY_ENVIRONMENT = "production"

# [secrets]
# SENTRY_DSN
# SENTRY_CLIENT_ID
# SENTRY_CLIENT_SECRET
