name: check

on:
  workflow_dispatch:
    inputs:
      sha:
        description: The SHA-1 hash referring to the commit to check.
        required: true
      ref:
        description: The head branch associated with the pull request.
        required: true
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
        env:
          GRAPHQL_ENDPOINT: https://pkmn-team.graphcdn.app

      - name: Tests
        run: npm run test

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: "build-storybook"
          exitZeroOnChanges: true
          exitOnceUploaded: true
          autoAcceptChanges: "main"
